from fastapi import APIRouter, HTTPException, status, Depends, Path
from typing import List
import uuid

from app.core import get_supabase_client, AuthenticatedUser, get_current_authenticated_doctor # Updated imports
from supabase import Client

from app.models.user import MedicalInfoDB, MedicalInfoCreate # MedicalInfoUpdate is defined but not used yet

router = APIRouter(
    prefix="/doctors",
    tags=["doctors"]
)

# Removed: async def get_current_doctor_id_from_path...
# Removed: async def get_target_user_id_from_path... (user_id will still be from path, but Path(...) is clearer)


@router.post(
    "/me/users/{user_id}/medical-info", # Path updated
    response_model=MedicalInfoDB,
    status_code=status.HTTP_201_CREATED
)
async def record_user_medical_info_by_doctor( # Renamed function
    medical_info_payload: MedicalInfoCreate,
    user_id: uuid.UUID = Path(..., description="The ID of the user (patient) for whom medical info is being recorded"), # user_id from path
    current_doctor: AuthenticatedUser = Depends(get_current_authenticated_doctor), # Use new auth dep for doctor
    supabase: Client = Depends(get_supabase_client)
):
    '''
    Allows an authenticated doctor to record new medical information for a specific user (patient).
    '''
    doctor_id = current_doctor.id # Get doctor_id from authenticated doctor's token
    print(f"Authenticated Doctor {doctor_id} attempting to record medical info for user {user_id}")

    # Optional: Further validation if this doctor is allowed to access/update this specific user_id's records.
    # This might involve checking a doctor-patient relationship table, which is beyond current scope.

    record_data = medical_info_payload.model_dump()
    record_data["user_id"] = str(user_id)
    record_data["doctor_id"] = str(doctor_id)
    # medical_record_id will be generated by DB

    try:
        response = supabase.table("medical_records").insert(record_data).execute()

        print(f"Supabase insert response for medical_records: {response}")

        if response.data:
            return MedicalInfoDB(**response.data[0])
        elif response.error:
            print(f"Supabase error: {response.error.message if response.error else 'Unknown error'}")
            if "violates foreign key constraint" in (response.error.message or "") and "medical_records_user_id_fkey" in (response.error.message or ""):
                 raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"User (patient) with ID {user_id} not found.")
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=response.error.message or "Failed to record medical info.")
        else:
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Unexpected error during medical record creation.")

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error recording medical info for user {user_id} by doctor {doctor_id}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.get(
    "/me/users/{user_id}/medical-info", # Path updated
    response_model=List[MedicalInfoDB]
)
async def get_user_medical_info_records_by_doctor( # Renamed function
    user_id: uuid.UUID = Path(..., description="The ID of the user (patient) whose medical info is being retrieved"), # user_id from path
    current_doctor: AuthenticatedUser = Depends(get_current_authenticated_doctor), # Use new auth dep for doctor
    supabase: Client = Depends(get_supabase_client)
):
    '''
    Allows an authenticated doctor to retrieve all medical information records for a specific user (patient).
    '''
    doctor_id = current_doctor.id # Get doctor_id from authenticated doctor's token (for logging or audit if needed)
    print(f"Authenticated Doctor {doctor_id} attempting to retrieve medical info for user {user_id}")

    # Optional: Further validation if this doctor is allowed to view this specific user_id's records.

    try:
        response = supabase.table("medical_records").select("*").eq("user_id", str(user_id)).execute()
        # If you wanted to also filter by doctor_id (e.g., doctor can only see records they created):
        # response = supabase.table("medical_records").select("*").eq("user_id", str(user_id)).eq("doctor_id", str(doctor_id)).execute()

        print(f"Supabase select response for medical_records: {response}")

        if response.data:
            return [MedicalInfoDB(**record) for record in response.data]
        elif response.error:
            print(f"Supabase error: {response.error.message if response.error else 'Unknown error'}")
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=response.error.message or "Failed to retrieve medical info.")
        else:
            return [] # No data and no error means empty list

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error retrieving medical info for user {user_id} by doctor {doctor_id}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))
