from fastapi import APIRouter, HTTPException, status, Depends, Path # Added Path
from typing import List # Keep this
import uuid

from app.core import get_supabase_client
from supabase import Client

# Import the new MedicalInfo models
from app.models.user import MedicalInfoDB, MedicalInfoCreate, MedicalInfoUpdate
# We might need UserProfileDB or Doctor model if we want to verify doctor/user existence beyond just IDs.
# from app.models.user import UserProfileDB, Doctor as DoctorModel # Renamed to DoctorModel to avoid var name conflict

router = APIRouter(
    prefix="/doctors",
    tags=["doctors"]
)

# Placeholder for actual doctor authentication.
# For now, we'll just use doctor_id from path.
# In a real app, a dependency would validate a JWT and confirm the user is a doctor
# and that their doctor_id matches the path or they have permissions.
async def get_current_doctor_id_from_path(doctor_id: uuid.UUID = Path(...)) -> uuid.UUID:
    # Add checks if doctor_id from path matches an authenticated doctor from a token
    return doctor_id

# We'll use a similar pattern for user_id from path as a placeholder
async def get_target_user_id_from_path(user_id: uuid.UUID = Path(...)) -> uuid.UUID:
    return user_id


@router.post(
    "/{doctor_id}/users/{user_id}/medical-info",
    response_model=MedicalInfoDB,
    status_code=status.HTTP_201_CREATED
)
async def record_user_medical_info(
    medical_info_payload: MedicalInfoCreate,
    doctor_id: uuid.UUID = Depends(get_current_doctor_id_from_path),
    user_id: uuid.UUID = Depends(get_target_user_id_from_path),
    supabase: Client = Depends(get_supabase_client)
):
    '''
    Allows a doctor to record or update (upsert) medical information for a specific user.
    A unique `medical_record_id` will be generated by the database for new records.
    If you want to update an *existing specific* record, a PUT to /medical-info/{record_id} would be more RESTful.
    This POST endpoint could behave as an "add new record" or "replace latest existing based on user_id" (upsert on user_id).
    For simplicity, let's assume an "upsert" based on user_id, implying one main medical record per user managed by this endpoint.
    If multiple records per user are expected, then POST should always create, and PUT used for specific updates.
    Let's refine this to: POST creates a new record. A separate PUT endpoint would update.
    For this iteration, POST will create. We'll assume one primary medical record per user for simplicity of GET.
    '''
    print(f"Doctor {doctor_id} attempting to record medical info for user {user_id}")

    # TODO: Add validation:
    # 1. Check if doctor_id corresponds to an actual, authenticated doctor.
    # 2. Check if user_id corresponds to an actual user. (e.g., query user_profiles or auth.users)

    record_data = medical_info_payload.model_dump()
    record_data["user_id"] = str(user_id)
    record_data["doctor_id"] = str(doctor_id)
    # medical_record_id will be generated by DB

    try:
        response = supabase.table("medical_records").insert(record_data).execute()

        print(f"Supabase insert response for medical_records: {response}")

        if response.data:
            return MedicalInfoDB(**response.data[0])
        elif response.error:
            print(f"Supabase error: {response.error}")
            # Example: Check for foreign key violation if user_id doesn't exist
            if "violates foreign key constraint" in response.error.message and "medical_records_user_id_fkey" in response.error.message:
                 raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"User with ID {user_id} not found.")
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=response.error.message)
        else:
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Unexpected error during medical record creation.")

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error recording medical info for user {user_id} by doctor {doctor_id}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.get("/{doctor_id}/users/{user_id}/medical-info", response_model=List[MedicalInfoDB])
async def get_user_medical_info_records( # Renamed to reflect it might return multiple records
    doctor_id: uuid.UUID = Depends(get_current_doctor_id_from_path),
    user_id: uuid.UUID = Depends(get_target_user_id_from_path),
    supabase: Client = Depends(get_supabase_client)
):
    '''
    Allows a doctor to retrieve all medical information records for a specific user.
    Sorted by creation time descending (most recent first), if a timestamp column like 'created_at' exists.
    For now, no specific sorting if 'created_at' is not assumed.
    '''
    print(f"Doctor {doctor_id} attempting to retrieve medical info for user {user_id}")

    # TODO: Add validation that doctor_id is authorized to view user_id's records.

    try:
        # Fetch all records for the user. If you want only the latest, you'd order and limit.
        # response = supabase.table("medical_records").select("*").eq("user_id", str(user_id)).order("created_at", desc=True).limit(1).single().execute() # For single latest
        response = supabase.table("medical_records").select("*").eq("user_id", str(user_id)).execute()

        print(f"Supabase select response for medical_records: {response}")

        if response.data:
            return [MedicalInfoDB(**record) for record in response.data]
        # It's not an error if there are no medical records, just an empty list.
        elif response.error:
            print(f"Supabase error: {response.error}")
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=response.error.message)
        else: # No data and no error means empty list
            return []

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error retrieving medical info for user {user_id}: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))
