# In app/models/user.py
from pydantic import BaseModel, EmailStr, Field
from typing import Optional, List, Dict, Any # Added Dict, Any
import uuid

# --- Authentication Models (moved from auth.py for centralization) ---
class UserCreateAPI(BaseModel): # Renamed from UserCreate to avoid conflict if User model also has 'email'
    email: EmailStr
    password: str = Field(..., min_length=6) # Added min_length for example

class UserLoginAPI(BaseModel): # Renamed from UserLogin
    email: EmailStr
    password: str

class AuthResponseAPI(BaseModel): # Renamed from AuthResponse
    message: str
    user_id: str | None = None
    access_token: str | None = None
    token_type: str | None = "bearer"

# --- User Profile Models ---
class UserProfileBase(BaseModel):
    # user_id is the primary key and typically the same as auth.users.id
    # It's often not part of the create/update payload directly from client if tied to auth user
    objectives: Optional[List[str]] = Field(None, example=["gain muscle", "lose weight"])
    experience_level: Optional[str] = Field(None, example="intermediate")
    # Using Dict[str, Any] for preferences for flexibility, could be more specific
    preferences: Optional[Dict[str, Any]] = Field(None, example={"preferred_gym_days": ["Mon", "Wed", "Fri"]})

class UserProfileCreate(UserProfileBase):
    # user_id will be taken from the path parameter (authenticated user)
    pass

class UserProfileUpdate(UserProfileBase):
    # All fields are optional for updates
    objectives: Optional[List[str]] = Field(None, example=["gain muscle", "lose weight"])
    experience_level: Optional[str] = Field(None, example="intermediate")
    preferences: Optional[Dict[str, Any]] = Field(None, example={"preferred_gym_days": ["Mon", "Wed", "Fri"]})


class UserProfileDB(UserProfileBase):
    user_id: uuid.UUID # This is the PK, same as auth.users.id
    email: Optional[EmailStr] = None # Email can be joined from auth.users table or stored here too
    # created_at: Optional[datetime] = None
    # updated_at: Optional[datetime] = None

    class Config:
        orm_mode = True # For compatibility if using an ORM or ORM-like responses

# --- Doctor and MedicalInfo Models (simplified for now, focus on UserProfile) ---
class Doctor(BaseModel): # Simplified, expand as needed
    doctor_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    email: EmailStr = Field(..., example="doc@example.com")
    name: Optional[str] = Field(None, example="Dr. John Doe")

# --- Medical Information Models ---
class MedicalInfoBase(BaseModel):
    # user_id and doctor_id will often come from path parameters or authenticated context
    conditions: Optional[List[str]] = Field(None, example=["hypertension", "past knee injury"])
    limitations: Optional[List[str]] = Field(None, example=["avoid high-impact exercises"])
    recommendations: Optional[str] = Field(None, example="Focus on low-impact cardio and strength training.")

class MedicalInfoCreate(MedicalInfoBase):
    # When creating, we might not have a medical_info_id yet if it's generated by DB
    # user_id and doctor_id will be injected from path or context
    pass

class MedicalInfoUpdate(MedicalInfoBase):
    # All fields are optional for an update
    conditions: Optional[List[str]] = None
    limitations: Optional[List[str]] = None
    recommendations: Optional[str] = None

class MedicalInfoDB(MedicalInfoBase):
    medical_record_id: uuid.UUID # Changed from medical_info_id for clarity if table is medical_records
    user_id: uuid.UUID
    doctor_id: uuid.UUID # Assuming doctors are users or have UUIDs stored somewhere
    # created_at: Optional[datetime] = None
    # updated_at: Optional[datetime] = None

    class Config:
        orm_mode = True
